name: example-environment
channels:
  - conda-forge
dependencies:
  - python 3.9.13
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - scipy
  - statsmodels
  - voila
  - ipywidgets
  - ipython
  - image
